import time
print(' ' * 15 + '|' + '|')
time.sleep(0.2)
print(' ' * 14 + '|' + ' ' * 1 + '|')
time.sleep(0.2)
print(' ' * 13 + '|' + ' ' * 2 + '|')
time.sleep(0.2)
print(' ' * 13 + '|' + ' ' * 3 + '|')
time.sleep(0.2)
print(' ' * 14 + '|' + ' ' * 4 + '|')
time.sleep(0.2)
print(' ' * 15 + '|' + ' ' * 5 + '|')
time.sleep(0.2)
print(' ' * 16 + '|' + ' ' * 6 + '|')
time.sleep(0.2)
print(' ' * 17 + '|' + ' ' * 7 + '|')
time.sleep(0.2)
print(' ' * 17 + '|' + ' ' * 8 + '|')
time.sleep(0.2)
print(' ' * 16 + '|' + ' ' * 10 + '|')
time.sleep(0.2)
print(' ' * 15 + '|' + ' ' * 11 + '|')
time.sleep(0.2)
print(' ' * 14 + '|' + ' ' * 10 + '|')
time.sleep(0.2)
print(' ' * 13 + '|' + ' ' * 10 + '|')
time.sleep(0.2)
print(' ' * 12 + '|' + ' ' * 11 + '|')
time.sleep(0.2)
print(' ' * 11 + '|' + ' ' * 12 + '|')
time.sleep(0.2)
print(' ' * 10 + '|' + ' ' * 12 + '|')
time.sleep(0.2)
print(' ' * 9 + '|' + ' ' * 12 + '|')
time.sleep(0.2)
print(' ' * 8 + '|' + ' ' * 12 + '|')
time.sleep(0.2)
print(' ' * 6 + '|' + ' ' * 13 + '|')
time.sleep(0.2)
print(' ' * 5 + '|' + ' ' * 14 + '|')
time.sleep(0.2)
print(' ' * 4 + '|' + ' ' * 15 + '|')
time.sleep(0.2)
print(' ' * 2 + '|' + ' ' * 16 + '|')
time.sleep(0.2)
print(' ' * 1 + '|' + ' ' * 17 + '|')
time.sleep(0.2)
print('|' + ' ' * 18 + '|')
time.sleep(0.2)
print('|' + ' ' * 19 + '|')
time.sleep(0.2)
print('|' + ' ' * 20  + '|')
time.sleep(0.2)
print('|' + ' ' * 20 + '|')
time.sleep(0.2)
time_2 = 0
while time_2 < 1:
    time_1 = 0
    for place_1 in range(10):
        print(' ' * place_1 + '|' + ' ' * 20 + '|')
        time.sleep(0.2)
    while time_1 < 4:
        print(' ' * 10 + '|' + ' ' * 20 + '|')
        time_1 = time_1 + 1
        time.sleep(0.2)
    for place_1 in range(10, 0, -1):
        print(' ' * place_1 + '|' + ' ' * 20 + '|')
        time.sleep(0.2)
    time_1 = 0
    while time_1 < 4:
        print('|' + ' ' * 20 + '|')
        time_1 = time_1 + 1
        time.sleep(0.2)
    time_2 = time_2 + 1
time_1 = 0
for place_1 in range(10):
    print(' ' * place_1 + '|' + ' ' * 20 + '|')
    time.sleep(0.2)
while time_1 < 4:
    print(' ' * 10 + '|' + ' ' * 20 + '|')
    time_1 = time_1 + 1
    time.sleep(0.2)
print(' ' * 9 + '|' + ' ' * 22 + '|')
time.sleep(0.2)
print(' ' * 8 + '|' + ' ' * 24 + '|')
time.sleep(0.2)
print(' ' * 7 + '|' + ' ' * 26 + '|')
time.sleep(0.2)
print(' ' * 5 + '|' + ' ' * 30 + '|')
time.sleep(0.2)
print(' ' * 5 + '|' + ' ' * 9 + '@' + ' ' * 10 + '@' + ' ' * 9 + '|')
time.sleep(0.2)
print(' ' * 5 + '|' + ' ' * 30 + '|')
time.sleep(0.2)
print(' ' * 7 + '|' + ' ' * 26 + '|')
time.sleep(0.2)
print(' ' * 8 + '|' + ' ' * 24 + '|')
time.sleep(0.2)
print(' ' * 10 + '|' + ' ' * 20 + '|')
time.sleep(0.2)
print(' ' * 11 + '|' + ' ' * 18 + '|')
time.sleep(0.2)
print(' ' * 12 + '|' + ' ' * 16 + '|')
time.sleep(0.2)
print(' ' * 14 + '|' + ' ' * 12 + '|')
time.sleep(0.2)
print(' ' * 15 + '_' * 2 + ' ' * 8 + '_' * 2)
time.sleep(0.2)
print(' ' * 17 + '_' * 8)
time.sleep(0.2)
print('                   | |')
time.sleep(0.2)
print('                  | |')
time.sleep(0.2)
print('                   | |')
time.sleep(0.2)
print('                    | |')
time.sleep(0.2)
print('                     W')